# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-2022

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: |
          server/package-lock.json
          client/package-lock.json
        cache: 'npm'

    - name: Install client
      working-directory: ./client
      run: npm ci
    
    - name: Install Server
      working-directory: ./server
      run: npm ci

    - name: Run client tests
      working-directory: ./client
      run: npm test

    - name: Run server tests
      working-directory: ./server
      run: npm test
